sudo: false

notifications:
  email: false

# there are specs in integration_tests but no spec_helper
# perhaps move it to standard 'spec' folder and have a spec_helper???
# it seems to rely on an existing database

bundler_args: --without production

rvm:
  - 2.5.3 # what's on the production VM as of 2018-11-13
cache: bundler
