sudo: false

notifications:
  email: false

# there are specs in integration_tests but no spec_helper
# perhaps move it to standard 'spec' folder and have a spec_helper???
# it seems to rely on an existing database

bundler_args: --without production

rvm:
  - 2.2.4 # what's on the production VM as of 2018-06-12
  - 2.3.7
  - 2.4.4

cache: bundler
